# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skladnik', to='menu.Pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.CharField(default=b'zwykla', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=b'DefaultIngredient', max_length=100, verbose_name=b'skladnik'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default=b'DefaultPizza', max_length=100, verbose_name=b'pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
