# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170601_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skladnik', to='menu.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=b'Default Ingredient', max_length=100, verbose_name=b'skladnik'),
        ),
    ]
