# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170601_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(default=b'skladniki', max_length=300),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(default=b'brak', max_length=100),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
